# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np

a = np.random.random((3,3,3))
a

array([[[0.06241028, 0.10459178, 0.24645971],
        [0.40973566, 0.57850016, 0.57164907],
        [0.7270337 , 0.09554593, 0.29921571]],

       [[0.37973895, 0.08970016, 0.9822355 ],
        [0.42675205, 0.04682232, 0.3872606 ],
        [0.39562861, 0.36049986, 0.65096741]],

       [[0.63611484, 0.36458924, 0.80001707],
        [0.34284464, 0.66836457, 0.6145728 ],
        [0.94932683, 0.63382394, 0.65206103]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
a = np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
a = np.ones((3,3))
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [10]:
a = np.random.random((5,5))
print("Before")
print(a)
amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)
print("After normalization:")
print(a)

Before
[[0.64189487 0.10137274 0.24718102 0.39042041 0.20545007]
 [0.55257207 0.65115534 0.54076193 0.73077535 0.99710091]
 [0.6715178  0.536782   0.12674773 0.22804017 0.6701381 ]
 [0.25158858 0.88117466 0.53628829 0.09862153 0.21221669]
 [0.21599094 0.04946655 0.54889069 0.70330514 0.61958583]]
After normalization:
[[0.62516551 0.05477448 0.20864004 0.35979474 0.16460306]
 [0.53090679 0.63493771 0.51844403 0.71895746 1.        ]
 [0.65642538 0.51424417 0.08155168 0.18844148 0.65496944]
 [0.21329116 0.87766774 0.51372318 0.05187124 0.1717436 ]
 [0.17572642 0.         0.52702198 0.68996927 0.60162369]]


# 5.  How to find common values between two arrays?

In [13]:
a = np.array([11,22,55,77,45,65,68])
print("Array a: ",a)
      
      
b = np.array([12,55,44,77,89,36,25,15])
print("Array b: ",b)
      
      
print("Common values between two arrays are:")
print(np.intersect1d(a, b))

Array a:  [11 22 55 77 45 65 68]
Array b:  [12 55 44 77 89 36 25 15]
Common values between two arrays are:
[55 77]


# 6.How to get the dates of yesterday, today and tomorrow?

In [15]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)

today = np.datetime64('today', 'D')
print("Today: ",today)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [23]:
a = np.random.randint(0,3,8)
print("First array:")
print(a)

b = np.random.randint(0,3,8)
print("Second array:")
print(b)

print("Test above two arrays are equal or not!")
equal = np.allclose(a, b)
print(equal)

First array:
[1 2 2 1 1 0 1 0]
Second array:
[0 0 1 0 2 1 0 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [25]:
a = np.random.random(10)
print("Array: ")
print(a)

a[a.argmax()] = 0
print("Maximum value replaced by 0:")
print(a)

Array: 
[0.32010365 0.96295989 0.86081631 0.03602764 0.0713552  0.05766768
 0.53266778 0.27222352 0.31602308 0.01453988]
Maximum value replaced by 0:
[0.32010365 0.         0.86081631 0.03602764 0.0713552  0.05766768
 0.53266778 0.27222352 0.31602308 0.01453988]


# 9. How to print all the values of an array?

In [26]:
import sys
a = np.arange(50)
np.set_printoptions(threshold=sys.maxsize)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


# 10.Subtract the mean of each row of a matrix

In [28]:
print("Matrix: ")
a = np.random.rand(3,3)
print(a)
print("\nSubtract the mean of each row of the said matrix:\n")
b = a - a.mean(axis=1, keepdims=True)
print(b)

Matrix: 
[[0.75405499 0.78764958 0.81001105]
 [0.10932116 0.90995055 0.04781883]
 [0.5521806  0.50695055 0.55100641]]

Subtract the mean of each row of the said matrix:

[[-0.02985021  0.00374438  0.02610584]
 [-0.24637569  0.5542537  -0.30787802]
 [ 0.01546808 -0.02976197  0.01429389]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [35]:
a = np.ones(5)
print(a)

b = np.random.randint(0,len(a),10)
print(b)

a += np.bincount(b, minlength=len(a))
print(a)

[1. 1. 1. 1. 1.]
[4 2 1 0 1 2 3 1 0 0]
[4. 4. 3. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [42]:
a = np.arange(9).reshape(3, 3)
print(a,"\n")

b = np.arange(9).reshape(3, 3)
print(b,"\n")

c = np.diag(a.dot(b))
print(c) 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[ 15  54 111]


# 13.How to find the most frequent value in an array?

In [46]:
a = np.random.randint(0, 10, 20)
print("Array:")
print(a)

print("Most frequent value in the above array:")
print(np.bincount(a).argmax())

Array:
[3 7 7 7 9 7 8 9 9 9 8 2 7 6 5 3 5 9 2 2]
Most frequent value in the above array:
7


# 14.How to get the n largest values of an array

In [63]:
a = np.array([2,5,88,99,101,54,65,74,35,28,45])
print("Array:")
print(a)
n = 1
print("Maximum value is:")
print (a[np.argsort(a)[-n:]])

Array:
[  2   5  88  99 101  54  65  74  35  28  45]
Maximum value is:
[101]


# 15.How to create a record array from a regular array?

In [65]:
a = np.array(['Machine','Learning','Engineer'])
b = np.array([99,55,11])
c = np.array(['p','q','r'])
records= np.core.records.fromarrays([a, b, c])
print(result[0])
print(result[1])
print(result[2])

('Machine', 99, 'p')
('Learning', 55, 'q')
('Engineer', 11, 'r')
